In [ ]:
import numpy as np

## Matrix as a `NumPy` array

Everything in `NumPy` is an array. A matrix is also an array. The main difference is that a matrix is a two dimensional array. Let us create a simple matrix:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
M = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Adding two matrices

Let us now add the following matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} + \textbf{B}  = \begin{bmatrix}
6 & 8\\
10 & 12
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
C

array([[ 6,  8],
       [10, 12]])

## Scaling a matrix

Scaling a matrix is nothing but element-wise multiplication:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

then,

$$
3 \textbf{M} = \begin{bmatrix}
3 & 6 & 9\\
12 & 15 & 18\\
21 & 24 & 27
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
3 * M

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])