In [1]:
import numpy as np

## Arrays

It should have become amply clear by now that both vectors and matrices are `NumPy` arrays. Each array in `NumPy` has a dimension. Vectors are one-dimensional arrays while matrices are two-dimensional arrays. For example:

$$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix},
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

`NumPy` arrays have an attribute called `ndim` that gives the number of dimensions of the array:

In [ ]:
M = np.array([[1, 2], [3, 4], [5, 6]])
x = np.array([1, 2, 3])

print("Shape of M is", M.shape)
print("Shape of x is", x.shape)

print("M is an array of dimension", M.ndim)
print("x is an array of dimension", x.ndim)

Shape of M is (3, 2)
Shape of x is (3,)
M is an array of dimension 2
x is an array of dimension 1


Though we will mostly restrict ourselves to arrays of dimension 2, nothing stops us from working with higher dimensional arrays. For example, consider a 3-dimensional array. This could be visualized as a list of matrices:

$$
\begin{bmatrix}
\begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12
\end{bmatrix}\\
\begin{bmatrix}
13 & 14 & 15 & 16\\
17 & 18 & 19 & 20\\
21 & 22 & 23 & 24
\end{bmatrix}\\
\end{bmatrix}
$$

This would be a $2 \times 3 \times 4$ array. In `NumPy` this becomes:

In [ ]:
M = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
M

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Reshaping

Arrays can be reshaped. We will start with an example. Let us start with a matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

We can now reshape it into a vector:

$$
\mathbf{x} = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$



In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6]])
x = M.reshape(6)

Note that the contents of the array are the same, but they have been rearranged. We can also go the other way, from vector to matrix:

$$
\mathbf{x} = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

We can reshape it into the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
M = x.reshape(3, 2)
M

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
M = x.reshape(3, 2) # will throw ValueError: cannot reshape array of size 7 into shape (3,2)

ValueError: cannot reshape array of size 7 into shape (3,2)

We can reshape a matrix into another matrix as well. Sometimes, we may not want to specify the dimensions completely. In such cases, we can let `NumPy` figure it out. For example

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

Let us say we want to reshape it in such a way that there are three rows:

$$
\mathbf{P} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$



In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6]])
P = M.reshape(3, -1)
P

array([[1, 2],
       [3, 4],
       [5, 6]])

$-1$ refers to the unknown dimension, which we let `NumPy` compute.

## Matrix-vector addition (broadcasting)

In many ML models, we would have to add a vector to each row or column of a matrix. For example, consider the following case for row-wise addition:


### Row-wise addition

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1 & 1 & 1 & 1
\end{bmatrix}
$$

This is slight abuse of notation as we can't add a matrix and a vector together. However, the context often makes this clear:

$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 3 & 4 & 5\\
6 & 7 & 8 & 9
\end{bmatrix}
$$

In `NumPy` this becomes:

In [ ]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 1, 1, 1])

print("shape of M:", M.shape)
print("shape of b:", b.shape)

M + b

shape of M: (2, 4)
shape of b: (4,)


array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

Notice how simple this is. Let us now do a slight variation. Let us say we wish to add a vector to each column of $\mathbf{M}$:

## Column-wise addition

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1\\
2
\end{bmatrix}
$$

In the case, we have:

$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 3 & 4 & 5\\
7 & 8 & 9 & 10
\end{bmatrix}
$$

Let us see if the same syntax works:

In [ ]:
M = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
b = np.array([1, 2])

M + b # this throws ValueError: operands could not be broadcast together with shapes (2,4) (2,)

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

If you uncomment it and run it, you get a ValueError. Notice that the same syntax doesn't work. The error is suggestive:

> operands could not be broadcast together with shapes `(2, 4)` and `(2, )`

We will first discuss a way to fix this and then move onto why this behaviour is observed.


## Indexing and Slicing an array

Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. For example, consider the matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$

The third row of this matrix is `M[2]`. This is just basic indexing.

In [ ]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[2]

array([5, 6])