## Import

First we shall import the `NumPy` package.

In [ ]:
import numpy as np

## Vectors as `NumPy` arrays

Consider the following vector:

$$
\boldsymbol{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$$

This is expressed as a `NumPy` array:

In [ ]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In the cell given above, `np.array` creates a `NumPy` array using a Python list that is passed as argument. Let us check the type of the object `x`:

In [ ]:
type(x)

numpy.ndarray

The term `ndarray` refers to an n-dimensional array. The idea of dimensions will become clear when we discuss matrices. For now, our focus will be one-dimensional arrays, or vectors.

## Vector addition

Addition is one of the elementary operations that can be performed on vectors. Given two vectors

$$
x = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, y = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$

we have:

$$
\boldsymbol{z} = \boldsymbol{x} + \boldsymbol{y}= \begin{bmatrix}
5\\
7\\
9
\end{bmatrix}
$$

In `NumPy` this is expressed as:

In [ ]:
y = np.array([4, 5, 6])
x + y

array([5, 7, 9])

## Element-wise multiplication

Element-wise multiplication of two vectors is called the Hadamard product. The operator corresponding to it is $\odot$. For example, given two vectors:

$$
x = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, y = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$

we have:

$$
\boldsymbol{z} = \boldsymbol{x} \odot \boldsymbol{y}= \begin{bmatrix}
4\\
10\\
18
\end{bmatrix}
$$

In `NumPy` this is expressed as:

In [ ]:
x*y

array([ 4, 10, 18])

## Scaling vectors

If $\boldsymbol{x}$ is a vector, scaling it by a constant $k$ is equivalent to element-wise multiplication by $k$. For example, given

$$
\boldsymbol{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$$

we have:

$$
b = 3 \boldsymbol{x} = \begin{bmatrix}
3\\
6\\
9
\end{bmatrix}
$$

As you might have guessed by now, in `NumPy` this is as simple as:

In [ ]:
b = 3 * x
b

array([3, 6, 9])

Again note that this is different from what you would expect with a Python list. The `*` operator for lists would result in replication. Besides, we can multiply a `NumPy` array by any real number, even $0$:

In [ ]:
b = 0 * x
b

array([0, 0, 0])

## Element-wise functions of vectors

Scaling a vector $\boldsymbol{x}$ by a constant $k$ can be seen as the output of the following function:

$$
f(\boldsymbol{x}) = \begin{bmatrix}
kx_1\\
\cdots\\
kx_m
\end{bmatrix}
$$

This is nothing but the function $f(x) = kx$ applied element-wise. `NumPy` extends this feature for any arbitrary function. For example, consider the function $g(x) = x^2$. This can be applied element-wise:

$$
g(\boldsymbol{x}) = \begin{bmatrix}
x_1^2\\
\cdots\\
x_m^2
\end{bmatrix}
$$

In `NumPy`, this translates to:

In [ ]:
b = x ** 2
b

array([1, 4, 9])

We can take up more complex functions as well. For example, let us take the case of `np.log10`, which is $\log_{10}$:

In [ ]:
a = np.array([10, 100, 1000, 10000])
b = np.log10(a)
b

array([1., 2., 3., 4.])

\Usually, we will stick to the natural logarithm or $\log_e$. This is given by `np.log`.

In [ ]:
a = np.array([1, np.e, np.e**2, np.e**3])
b = np.log(a)
b

array([0., 1., 2., 3.])

## Dot Product

The dot product between two vectors $\mathbf{x}$ and $\mathbf{y}$ is given as follows:

$$
z = \mathbf{x} \cdot \mathbf{y} = \sum \limits_{j = 1}^{m} x_j y_j
$$

In `NumPy`, this could be done as follows:

In [ ]:
np.dot(x, y)

np.int64(32)

## Shape of a vector

All `NumPy` arrays have an attribute called `shape`. The shape is a tuple. For vectors (single-dimensional) the shape is of the form $(n, )$, where $n$ is the number of components in the vector.

In [ ]:
x.shape

(3,)