# Numeric Transformers
* Feature Scaling
* polynomial transormation
* Discretization

# Feature Scaling
* Numeric features with different scales leads to slower convergence of iterative optimization procedures.
* It is a good practice to scale numeric features so that all of them are on the same scale.
* feature scaling API in sklearn:
    * StandardScalar
    * MaxAbsScalar
    * MinMaxScalar

### StandardScalar:
* transforms the feature vector into a new feature vector using

$$
x' = \frac{x - \mu}{\sigma}
$$




In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

data = np.array([[4], [3], [2], [5], [6]])
ss = StandardScaler()
ss.fit_transform(data)

array([[ 0.        ],
       [-0.70710678],
       [-1.41421356],
       [ 0.70710678],
       [ 1.41421356]])

note that the transformed feature vector now have mean = 0 and sd = 1.

### MinMaxScalar
* it transforms the original vector to new feature vector so that all the values lie in range [0, 1]

$$
x' = \frac{x - x.min}{x.max - x.min}
$$

In [2]:
from sklearn.preprocessing import MinMaxScaler

data = np.array([[15],[2], [5], [-2], [-5]])

mms = MinMaxScaler()
mms.fit_transform(data)

array([[1.  ],
       [0.35],
       [0.5 ],
       [0.15],
       [0.  ]])

* the largest number is transformed to 1 and the smallest to 0

### MaxAbsScalar
* * it transforms the original vector to new feature vector so that all the values lie in range [-1, 1]

$$
x' = \frac{x}{MaxAbsoluteValue}
$$

In [3]:
from sklearn.preprocessing import MaxAbsScaler

data = np.array([[4], [2], [5], [-2], [-100]])

mas = MaxAbsScaler()
mas.fit_transform(data)

array([[ 0.04],
       [ 0.02],
       [ 0.05],
       [-0.02],
       [-1.  ]])

### FunctionTransformer:
* transforming feature by using user defined function

In [4]:
from sklearn.preprocessing import FunctionTransformer

data = np.array([
    [128, 2],
    [2, 256],
    [4, 1],
    [512, 64]])

ft = FunctionTransformer(np.log2) # applies log2 function to the features
ft.fit_transform(data)

array([[7., 1.],
       [1., 8.],
       [2., 0.],
       [9., 6.]])

# Polynomial Transformations:
* generates a new feature matrix consisting of all the polynomial combinations of the features with degrees less than or equal to the specific degree.

$$
X = [x_1, x_2]
$$

```
pf = PolynomialTransformation()
pf.fit_transform(X)
```

$$
X' = [x_1, x_2, x_1x_2, x_1^2, x_2^2]
$$

### KBinsDiscretizer:
* divides a continuous variable into bins
* oneHotEncoding or OrdinalEncoding is applied to label the bins.

In [6]:
from sklearn.preprocessing import KBinsDiscretizer

data = np.array([[0], [0.125], [0.25], [0.375], [0.5], [0.675], [0.75], [0.875], [1]])

kbd = KBinsDiscretizer(
    n_bins = 5,
    strategy="uniform",
    encode="ordinal"
)
kbd.fit_transform(data)

array([[0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [3.],
       [3.],
       [4.],
       [4.]])